### ISSUE TITLE
can not git the repository

### ISSUE THREAD

**Issue by liuguaaa** [byu-holoocean/holoocean-docs#1]
Hi,i want to git the https://github.com/byu-holoocean/HoloOcean repository, and i have connected my github account with the Epic Game account according to the tutorial.But i still get a Page Not Found Error,i want to know how to solve this problem,thank u!

**Comment by Jayzhang2333** [comment]
same issue here. I have connected my github account to Epic and still geting page not found error

**Comment by Jayzhang2333** [comment]
just wondeirng, could this be due to the change of Epic organization repo? From 10th of JUne, the new user who linked their github account to Epic will only be invited to a secondary repo call EpicGame-Mirror-A.

**Comment by liuguaaa** [comment]
> just wondeirng, could this be due to the change of Epic organization repo? From 10th of JUne, the new user who linked their github account to Epic will only be invited to a secondary repo call EpicGame-Mirror-A.

Oh,i can find your name in EpicGame-Mirror-A,so did you find some methods to git the previous repo? If you have the method to solve the problem, please let me know.Thank u!

**Comment by BPelletier71** [comment]
Hi, I'm having the same problem here, can't access or clone the repository. I'm also in the EpicGame-Mirror-A group!

**Comment by AbiAustin** [comment]
Yes, I believe this is a problem caused by Epic's recent changes to their GitHub organization structure.

We have implemented a work around.

If you linked your account after June 10th (and thus were added to the Epic-Games-Mirror-A/developers team), you should be able to access and clone from https://github.com/byu-holocean-mirror/HoloOcean

Please let us know if you run into any issues.

**Comment by BlakePR** [comment]
we've updated the v1.0.0 docs it has this info as well, https://byu-holoocean.github.io/holoocean-docs/v1.0.0/usage/installation.html#stable-installation
