### ISSUE TITLE
Python Requriement

### ISSUE THREAD

**Issue by Jayzhang2333** [byu-holoocean/holoocean-docs#2]
Hi,
When I ran Holoocean's imaging sonar simulation with Python 3.6, the sonar image generated is incorrect. I saw that in the setup script,  the python requriement is >=3.7, so I think the incorrect sonar images is caused by some matrix transformation change from python 3.6 to 3.7. It might be better to change the python requirement in the documentation, whichc says '>=3.6' at the moment

**Comment by BlakePR** [comment]
This should be updated in the docs now.
