### ISSUE TITLE
Depth map generation

### ISSUE THREAD

**Issue by Jayzhang2333** [byu-holoocean/holoocean-docs#5]
Hi there, the simulator is fantastic and it runs pretty well. I am just wondering if the HoloOcean simulator can also provide ground truth depth image for the RGB camera?

**Comment by BlakePR** [comment]
We are in the process of adding a depth camera; @sonorousduck is working on that currently, but it is not yet in the develop branch, or in a stable working state. We will update you when that changes, should be soon

**Comment by Jayzhang2333** [comment]
That sounds great! Hopefully it will release soon.
