### ISSUE TITLE
None of the HoloOcean Repos are visible

### ISSUE THREAD

**Issue by elishafer** [byu-holoocean/holoocean-docs#7]
My github account is linked to Epic Games and I've previously cloned HoloOcean. I can't see the HoloOcean repo or the mirror repo. I've checked both on Epic Games and github that my account is linked and that I'm a member of Epic Games in github.

**Comment by AbiAustin** [comment]
Did you previously clone HoloOcean from the Bitbucket before we transitioned to GitHub? If you did clone from GitHub, was it from the mirror or main HoloOcean repo?

What developer group are you a member of? Did you accept the email invite to link you accounts?

**Comment by elishafer** [comment]
It seems that the repo is hidden (it's not in the byu-holoocean repo lists) and can only be accessed via a link or directly entering the url.
Here's the [link](https://github.com/byu-holoocean/HoloOcean) for future reference
Sorry for causing a fuss about it, closing the issue now
