### ISSUE TITLE
None of the HoloOcean Repos are visible - I guess again :/

### ISSUE THREAD

**Issue by Bender97** [byu-holoocean/holoocean-docs#9]
Even after having connected the GitHub account to EpicGames, the new link
git clone git@github.com:byu-holoocean-mirror/HoloOcean.git holoocean
is not working: error 404.

The old link gives 404 too.

Is there a workaround?

Thanks, Daniel.

**Comment by BlakePR** [comment]
The epic games issue has been resolved, so if you've linked your account to epicgames you should be able to access at: https://github.com/byu-holoocean/HoloOcean
